[workspace]
resolver = "2"
members = [
  "dpdk-net",
  "dpdk-net-test",
]

[workspace.dependencies]
rpkt-dpdk = { git = "https://github.com/duanjp8617/rpkt.git", rev = "ab79697ddc9fbae1a545d16fe68098f8e6ad3b87" }
ctrlc = "3"
smoltcp = { version = "0.12", features = ["async"] }
arrayvec = "0.7"
serial_test = "3"
nix = { version = "0.30", features = ["net"] }
tokio = "1"

# crate in this workspace
dpdk-net = { path = "dpdk-net" }
dpdk-net-test = { path = "dpdk-net-test" }