[package]
name = "dpdk-net"
version = "0.1.0"
edition = "2024"

[dependencies]
smoltcp.workspace = true
arrayvec.workspace = true
rpkt-dpdk.workspace = true
tokio = { workspace = true, features = ["rt"] }