[package]
name = "dpdk-net-test"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
rpkt-dpdk.workspace = true
ctrlc.workspace = true
smoltcp.workspace = true
arrayvec.workspace = true
nix.workspace = true
dpdk-net.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "sync"] }

[dev-dependencies]
serial_test.workspace = true